### ISSUE TITLE
Velocity Support

### ISSUE THREAD

**Issue by BenCodez** [BenCodez/VotifierPlus#11]

**Comment by iamflorencejay** [comment]
When?

**Comment by BenCodez** [comment]
Whenever I get to it? There isn't really a rush since nuvotifier works on velocity

**Comment by iamflorencejay** [comment]
> Whenever I get to it? There isn't really a rush since nuvotifier works on velocity

Problem is, it is unmaintained in my opinion, or just waiting for a 1.19 and 1.18 build
