### ISSUE TITLE
Not sure if im doing something wrong

### ISSUE THREAD

**Issue by atomisgray** [BenCodez/VotifierPlus#21]
this is my config and im trying to allow votes from the minecraft server lists site (MCSL) i think i may have data in the wrong spot?

DebugLevel: NONE
host: 0.0.0.0
port: 40993
Forwarding:
  server1:
    Enabled: true
    Host: 'MCSL'
    Port: '40993'
    Key: ' the rsa public key'

**Comment by atomisgray** [comment]
I've never used a votifier plugin before so im not sure of the valid forwarding methods. do you have a discord or a wiki that shows examples? who do i forward to?

**Comment by BenCodez** [comment]
Yes. You should lookup votifier plugin tutorials, they all work the same pretty much.

**Comment by atomisgray** [comment]
im using your votingplugin along with votifierplus and i believe i can figure that one out with all the wikis and tutorials, i was just very confused that my console wasnt picking up any votes through votifier. it picks up votes through the votingplugin but says nothing about votifier.

i only say all that because in a wiki for votingplugin you state that if i dont get this message in my console then votingplugin wont work

[19:01:21] [Votifier I/O/INFO]: [VotifierPlus] Debug: Received vote record -> Vote (from:SERVICESITEHERE username:BenCodez address:Address timeStamp:TestVote)
[19:01:21] [Server thread/INFO]: [VotingPlugin] Received a vote from service site 'SERVICESITEHERE' by player 'BenCodez'!

well i only get the second half of that message so i'm confused haha

**Comment by atomisgray** [comment]
ok so do i have to enable debug in order for votingplugin to work? and if so how do i do that? would i replace NONE with enabled?

sorry for so many questions

**Comment by BenCodez** [comment]
you don't need to enabled debug. you set enabled to false
