### ISSUE TITLE
Not sure what this means. :p

### ISSUE THREAD

**Issue by TheGame120** [BenCodez/VotifierPlus#22]
Whenever i use the command /votifierplus <username> vote, it tells me to check the console for results, this is what i get:

at VotifierPlus.jar//com.vexsoftware.votifier.commands.CommandLoader$3.execute(CommandLoader.java:89)
31.05 00:28:40 [Server] WARN at VotifierPlus.jar//com.bencodez.VotifierPlus.advancedcore.api.command.CommandHandler$1.run(CommandHandler.java:446)
31.05 00:28:40 [Server] WARN at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
31.05 00:28:40 [Server] WARN at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
31.05 00:28:40 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
31.05 00:28:40 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
31.05 00:28:40 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
31.05 00:28:40 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)

Please help me, I have no idea what these mean

**Comment by BenCodez** [comment]
Gonna need more details

**Comment by TheGame120** [comment]
Like what? I don't really know what this means, so talk to me like I'm literally 6 years old.

**Comment by BenCodez** [comment]
Send your console logs from startup, configs, what your trying to do...

**Comment by TheGame120** [comment]
(Just FYI I'm using Apex hosting, like a mortal)
Here's the VotifierPlus startup console logs:
31.05 00:42:54 [Server] WARN [VotifierPlus] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.3-b131 which is not a depend or softdepend of this plugin.
31.05 00:42:54 [Server] INFO [VotifierPlus] Successfully hooked into vault economy!
31.05 00:42:54 [Server] INFO [VotifierPlus] Hooked into vault permissions
31.05 00:42:54 [Server] INFO [VotifierPlus] VotifierPlus is up to date! Version: 1.0.7

**Comment by TheGame120** [comment]
And i am literally just trying to setup voting through TopG.

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting check this. Don't worry about the error right now.

**Comment by TheGame120** [comment]
The IP address you use for the voting setup is the same as the server's ip, correct?

**Comment by BenCodez** [comment]
Generally, it can differ, ask your host for help, they should know better

**Comment by TheGame120** [comment]
ok
