### ISSUE TITLE
Error message when trying to vote

### ISSUE THREAD

**Issue by FlyingCow32** [BenCodez/VotifierPlus#24]
Hey i downloaded VotifierPlus on the server , and when i try to setup the vote system and try to test the vote , and it showup this error :
io.netty.handler.timeout.ReadTimeoutException

Can anyone know how to solve it ?
here are the config information :
![image](https://user-images.githubusercontent.com/107033721/172337131-2576ca9f-ee3c-490c-a343-b0a01332f672.png)

thanks for the help.

**Comment by BenCodez** [comment]
Use a different port

**Comment by BenCodez** [comment]
ask your host for what port to use

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting

**Comment by FlyingCow32** [comment]
im really sorry , but we did everything on this , we even tryied all the plugins and it still don't work , there is something but i don't find what , here is the error code , if you don't have idea of the problem solution , do you know what does it mean ? 
![image](https://user-images.githubusercontent.com/107033721/172451364-293e7bcd-776f-44a4-9966-981c8b73e7d0.png)

**Comment by BenCodez** [comment]
> im really sorry , but we did everything on this , we even tryied all the plugins and it still don't work , there is something but i don't find what , here is the error code , if you don't have idea of the problem solution , do you know what does it mean ? ![image](https://user-images.githubusercontent.com/107033721/172451364-293e7bcd-776f-44a4-9966-981c8b73e7d0.png)

I honestly got no idea right no now. Ask your host for a port.

**Comment by FlyingCow32** [comment]
he don't know too x) alright , imma ask to others server's owners , thanks for the fast support !
