### ISSUE TITLE
Error shutting down my server

### ISSUE THREAD

**Issue by alechretien16** [BenCodez/VotifierPlus#26]
Error when shutting down my server, I don't know why it is, I use a host for my server.

08.08 10:17:31 [Server] WARN Protocol error. Ignoring packet - Socket closed
08.08 10:17:31 [Server] WARN java.net.SocketException: Socket closed
08.08 10:17:31 [Server] WARN at java.base/sun.nio.ch.NioSocketImpl.endAccept(NioSocketImpl.java:689)
08.08 10:17:31 [Server] WARN at java.base/sun.nio.ch.NioSocketImpl.accept(NioSocketImpl.java:762)
08.08 10:17:31 [Server] WARN at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:675)
08.08 10:17:31 [Server] WARN at java.base/java.net.ServerSocket.platformImplAccept(ServerSocket.java:641)
08.08 10:17:31 [Server] WARN at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:617)
08.08 10:17:31 [Server] WARN at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:574)
08.08 10:17:31 [Server] WARN at java.base/java.net.ServerSocket.accept(ServerSocket.java:532)
08.08 10:17:31 [Server] WARN at VotifierPlus.jar//com.vexsoftware.votifier.net.VoteReceiver.run(VoteReceiver.java:131

**Comment by BenCodez** [comment]
Send startup log?

**Comment by alechretien16** [comment]
> Send startup log?

https://pastebin.com/kxVMEc3G

**Comment by BenCodez** [comment]
Is everything working as it should?

**Comment by alechretien16** [comment]
> Is everything working as it should?

Yes, everything perfectly!
I just wanted to report the problem, or at least know what it means.

**Comment by BenCodez** [comment]
Think maybe it got a vote on shutdown, or it shutdown while processing a vote, either way not a big problem

**Comment by alechretien16** [comment]
Oh ok, thanks!
