### ISSUE TITLE
ERROR: Unable to decrypt vote record.

### ISSUE THREAD

**Issue by MeanKid619** [BenCodez/VotifierPlus#31]
When I use [this](https://crafty.gg/tools/votifier) website the votes go through [fine](https://imgur.com/1aqkVSD.png) and shows the vote in [console](https://imgur.com/rekFKNT.png) but other sites I have tried such as [this](https://mcservertime.com/votifier-tester) give me "[votifier offline](https://imgur.com/taiTinW.png)" and the error "[Unable to decrypt vote record.](https://imgur.com/5s77jTg.png)" in console, and the key does in fact match.

**Comment by BenCodez** [comment]
Could delete your keys and let it generate new keys and see how that goes?

**Comment by MeanKid619** [comment]
The result is the same, I will share the key, ip and port if it helps in any way as this is a test server so it doesn't matter if anyone else has it.
Ipv4: 147.185.221.223
Domain: vote.mechacraft.playit.gg
Port: 16110
New public key: https://pastebin.com/PCeue2nd
rsa/public.key: https://imgur.com/w3EZYN0.png

**Comment by BenCodez** [comment]
There isn't anything I can do about this

**Comment by MeanKid619** [comment]
Alright.
