### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "com.vexsoftware.votifier.net.VoteReceiver.encrypt(byte[], java.security.PublicKey)"

### ISSUE THREAD

**Issue by Kxsumi** [BenCodez/VotifierPlus#33]
![image](https://user-images.githubusercontent.com/96434998/210669306-98ffca42-5103-476b-b49f-70d698b80584.png)
![image](https://user-images.githubusercontent.com/96434998/210669436-39675e8e-4c51-4934-a172-53085cf372d5.png)
Server IP is different than the one's I'm using for allocation, only because I don't have any ports open on the actual server IP
1.19.3
Paper

**Comment by BenCodez** [comment]
Startup log?

**Comment by Kxsumi** [comment]
> Startup log?

Nevermind all good, I put in 0.0.0.0 instead of the server IP and it works now. Except when i vote I have to test it to get it to register the vote which is weird

**Comment by Kxsumi** [comment]
Nevermind -- Here. 
https://mclo.gs/LI3XZ8A

**Comment by BenCodez** [comment]
Check this https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting

**Comment by Kxsumi** [comment]
> Check this https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting

Looked at it already. 
I can confirm:
My host does not have it blocked in the Firewall
The keys are valid because it does not work on either one of our servers (yes I did try to remake them) 
The port / IP is not being used at the same time as anything else. 
The IP is auto -- 0.0.0.0

**Comment by BenCodez** [comment]
Well there isn't really anything that I can do for you
