### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by avaoffiziell** [BenCodez/VotifierPlus#35]
Hello there, before it worked but something is wrong with my dependecy

        <dependency>
            <groupId>com.github.BenCodez</groupId>
            <artifactId>VotifierPlus</artifactId>
            <version>LATEST</version>
            <scope>provided</scope>
        </dependency>
        
        And can i get the <repository></repository>?
        
        I'm using VotifierPlus 1.0.7 with Spigot 1.19.2

**Comment by avaoffiziell** [comment]
Dependency 'com.github.BenCodez:VotifierPlus:LATEST' not found

**Comment by BenCodez** [comment]
try this:

    <repository>
        <id>BenCodez Repo</id>
        <url>https://nexus.bencodez.com/repository/maven-public/</url>
    </repository>

    <dependency>
        <groupId>com.bencodez</groupId>
        <artifactId>votifierplus</artifactId>
        <version>LATEST</version>
        <scope>provided</scope>
    </dependency>

**Comment by BenCodez** [comment]
or this:

    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>

    <dependency>
        <groupId>com.github.BenCodez</groupId>
        <artifactId>VotifierPlus</artifactId>
        <version>LATEST</version>
        <scope>provided</scope>
    </dependency>
