### ISSUE TITLE
Tutorials are inaccurate

### ISSUE THREAD

**Issue by GreenFlameblade** [BenCodez/VotifierPlus#46]
In the reviews section, someone complains about there not being an official tutorial for votifierplus. You responded saying that any votifier tutorial would suffice. However, your config system is significantly different, which leads to confusion. 

For example, in the below linked tutorial for nuvotifier, each server's config has a token that is used to connect the sub server to the proxy for receiving votes. This plugin does not include a token. I'm assuming that the token is the public key in the rsa folder, but that is not explained.

Second difference, in nuvotifier, only the proxy has forwarding options. In this plugin, all servers have forwarding options and there isn't a proxy setting. Do I need to put all the other servers including the proxy into the forwarding section of each server config? Does the plugin automatically detect the presence of a network proxy?

https://www.youtube.com/watch?v=E7E3NkX9lBU

**Comment by GreenFlameblade** [comment]
Also, when I input the port inside the quotes e.g. '12345', it errors out. I need to remove the quotes e.g. 12345 for the config to recognize the port. Otherwise, it defaults to exampleIP:0

**Comment by BenCodez** [comment]
> In the reviews section, someone complains about there not being an official tutorial for votifierplus. You responded saying that any votifier tutorial would suffice. However, your config system is significantly different, which leads to confusion.
> 
> For example, in the below linked tutorial for nuvotifier, each server's config has a token that is used to connect the sub server to the proxy for receiving votes. This plugin does not include a token. I'm assuming that the token is the public key in the rsa folder, but that is not explained.
> 
> Second difference, in nuvotifier, only the proxy has forwarding options. In this plugin, all servers have forwarding options and there isn't a proxy setting. Do I need to put all the other servers including the proxy into the forwarding section of each server config? Does the plugin automatically detect the presence of a network proxy?
> 
> https://www.youtube.com/watch?v=E7E3NkX9lBU

VotifierPlus is a fork of Votifier, not nuvotifier. Follow votifier tutorials. Only difference is VotifierPlus has a basic vote forwarder.



> Also, when I input the port inside the quotes e.g. '12345', it errors out. I need to remove the quotes e.g. 12345 for the config to recognize the port. Otherwise, it defaults to exampleIP:0

Putting it in quotes forces it to read as string (or text) rather than a number, it's a yaml thing
