### ISSUE TITLE
questions about the config

### ISSUE THREAD

**Issue by DueKay** [BenCodez/VotifierPlus#51]
Beautiful good day,

I have a question about the config, as integrating the votes seems to be much more extensive in Java than in Bedrock.

We actually had a Bedrock server, but were now forced to switch to Java because we can no longer work with Nukkit.
Now we finally wanted to include voting for users again, but it looks completely different here than on the Bedrock server. That's why I hope I can be helped here.

I have the plugin on our Velocity Server. In the bungeeconfig.yml I have now entered our IP under host and instead of server1 (which is default) the name of our server that is supposed to distribute the rewards. (currently only one server in the network, there will be more in the future, which is why it should work directly via Velocity)
I entered true under the server name for Enabled: but I'm unsure what needs to be added to the host, port and key.
And is it enough that I only have the plugin on the Velocity, or do I also have to put it on the Paper Server and set it up?

Of course, I know in the meantime that I also have to use the privat.key to integrate the voting websites, but I think I'll rather deal with the websites than get help from here and I wanted to deal with it , when I know that I have already set everything up correctly.

Then the voting plugin comes in, but one after the other. :)

Thank you very much for your time
Best regards
DueKay

Ps. sry if the translation is rather bad (google)

Schönen guten tag,

ich hätte eine Frage zu der config, da dass mit den Votes einbinden scheinbar in Java viel umfangreicher ist, als bei Bedrock.

Wir hatten eigentlich einen Bedrock Server, waren mittlerweile aber gezwungen auf Java umzustellen, da wir mit Nukkit nicht mehr weiter arbeiten können.
Nun wollten wir endlich wieder das Voten für User mit einbinden, doch das sieht hier gänzlich anders aus, als beim Bedrock Server. Deswegen hoffe ich, dass mir hier geholfen werden kann.

Ich habe das Plugin auf unserem Velocity Server liegen. In der bungeeconfig.yml habe ich jetzt bei host unsere IP eingegeben und statt server1 (was vorgegeben ist) den Namen unserers Servers, der die Belohnungen verteilen soll. (derzeit nur ein Server im Netzwerk, zukünftig sollen es weitere werden, weshalb es direkt über Velocity funktionieren sollte)
Unter den Servernamen hab ich bei Enabled: true eingegeben, doch ich bin mir unsicher was bei Host, Port und Key rein muss.
Und reicht es, dass ich das Plugin nur auf dem Velocity hab, oder muss ich es ebenfalls auf den Paper Server legen und einstellen?

Natürlich weiß ich derweil, dass ich den privat.key auch noch benutzen muss um die Vote Webseiten einzubinden, doch ich denke, da werde ich mich dann eher mit den Webseiten auseinander setzen, als dass ich dafür von hier Hilfe bekomme und wollte mich damit beschäftigen, wenn ich weiß, dass ich sonst schonmal alles richtig eingestellt habe.

Anschließend kommt dann noch das Voting-Plugin dran, aber eins nach dem anderen. :)

Vielen dank schonmal für Ihre Zeit
Liebe Grüße 
DueKay

Ps. sry wenn die Übersetzung eher schlecht ist (google)

**Comment by BenCodez** [comment]
If your using votingplugin you can use this setup: https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-PLUGINMESSAGING

**Comment by DueKay** [comment]
Nice good morning,

I was already looking to see if I could find something and also came across the page that you sent me as a link.
But unfortunately the example config and the one on our server look very different...
Maybe you could just write to me about what goes in there or whether it should remain free?
And whether I only need the plugin on the Velocity or also on the Paper servers?
I would be very happy.

This is our config:
Debug: false
host: 0.0.0.0 (I had our IP in here)
port: 8192
Forwarding:
  cbsky:
    Enabled: true
    Host: ''
    Port: ''
    Key: ''

And this is the one from the example:
# Set bungeecoord to true on servers on the network (In VotingPlugin)
# Set server name in each server related to what it is on bungee
#
# MYSQL Required on all setups
# MYSQL INFO --------------------------
Host: ''
# Default port is 3306
Port: 3306 
Database: ''
Username: ''
Password: ''
# Max number of connections
MaxConnections: 1
# Maxium size of caching mysql
# -1 for no limit
# Affecting this value may affect performance
MaxSize: -1
# Table name prefix, for use with mutliple servers
Prefix: ''
#UseSSL: true
#PublicKeyRetrieval: false

Debug: false
# Have a reward on each server
# If false, will send to online server only
SendVotesToAllServers: true
# List of servers the plugin won't send the vote to
# Uses names from bungeecoord config if not using SOCKETS method
BlockedServers:
- hub

# What type of bungee setup
# Requires restart and set on all servers
# https://github.com/Ben12345rocks/VotingPlugin/wiki/Bungeecoord-Setups
# Available:
# SOCKETS 
# PLUGINMESSAGING 
# MYSQL
BungeeMethod: PLUGINMESSAGING

FallBackServer: factions

AllowUnJoined: false


I'm not good at English and I always try to translate everything. But at that point I somehow got stuck...

Thank you in advance and kind regards
DueKay


Schönen guten Morgen,

Ich hatte selbst schon gesucht ob ich was finde und bin ebenfalls auf die Seite gestoßen, welche Sie mir als Link geschickt haben.
Doch leider sehen die Beispiel config und die auf unserem Server, sehr unterschiedlich aus...
Vielleicht könnten sie mir einfach schreiben, was da rein kommt oder ob es frei bleiben soll?
Und ob ich das Plugin nur auf dem Velocity brauche oder auch auf den Paper Servern?
Würde mich sehr freuen.

Ich bin nicht gut in Englisch und versuche mir immer alles zu übersetzen. Doch an dem Punkt bin ich irgendwie hängen geblieben....

Danke schonmal und liebe Grüße
DueKay

**Comment by DueKay** [comment]
...if I saw it correctly, I also need the plugin on every paper server. The config just gives me problems because it doesn't say anywhere what has to go there...
Maybe in the future you could add description lines to the bungeeconfig.yml that explain directly in the config what has to go where?


...wenn ich es richtig gesehen hab, brauch ich das Plugin auch auf jedem Paper Server. Die config macht mir nur Probleme, da nirgends definitiv steht, was dort hin muss...
Vielleicht könnten sie zukünftig in der bungeeconfig.yml Beschreibungs Zeilen hinzufügen, die direkt in der config erklären, was wo rein muss?

**Comment by BenCodez** [comment]
The wiki page I linked has the required settings that need to be set. Where are you having trouble right now?

**Comment by DueKay** [comment]
I wrote that I don't really know what to add to the config. Since there are no descriptions and the example config looks completely different and larger.

would have to know what needs to go in there
Host: ''
Port: ''
Key: ''

and since it varies from config to config, I would also ask whether I have to put what needs to go there in the '', or whether they will go away if I write something there?

Thanks in advance

**Comment by BenCodez** [comment]
You don't need to set that since your not using votifierplus forwarding

**Comment by DueKay** [comment]
That means host, port and key can remain empty?
But do I have to enter the IP at host? The one from the current server? Or should that stay at 0.0.0.0?

Thanks in advance

**Comment by DueKay** [comment]
And I need the plugin on all servers right? Or not, because the redirection is via another plugin?

**Comment by BenCodez** [comment]
Yes leave those settings blank. You have to do try and error with the ip.
Votifier Plus on proxy only and VotingPlugin on all the rest

**Comment by DueKay** [comment]
Thank you for your trouble.
If I understood this correctly:
I don't have to adjust anything in conig. Or that with the IP should I just try and see how it works!?
This plugin only on the proxy and the voting plugin on all papers where I want to award rewards?
The main task of the plugin is then to connect to the voting websites!?
If this is correct, the threat can be closed. And thank you again. The information saves me a headache. :)

**Comment by BenCodez** [comment]
you also want votingplugin on proxy, I'd try and see what happens

**Comment by DueKay** [comment]
No. I said the voting plugin would only be on the paper server.
Did I understand that correctly as I wrote about it in the post?
I'm also sorry about the English. Is translated with Google.

**Comment by BenCodez** [comment]
You need votingplugin on proxy and paper servers.

**Comment by Fr4nk117** [comment]
I also had doubts similar to those of DueKay (I am also using velocity) and from what I read, then Votifierplus should only go on the proxy and VotingPlugin should go on all the other servers including the proxy, and nothing is configured in Votifierplus, VotingPlugin should only be configured using the link provided as a guide in the previous comments, is that right?

**Comment by BenCodez** [comment]
> I also had doubts similar to those of DueKay (I am also using velocity) and from what I read, then Votifierplus should only go on the proxy and VotingPlugin should go on all the other servers including the proxy, and nothing is configured in Votifierplus, VotingPlugin should only be configured using the link provided as a guide in the previous comments, is that right?

Proxy needs votifier configured. https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-PLUGINMESSAGING
