### ISSUE TITLE
“Failed to fetch Minecraft player from Mojang, please try again later.”

### ISSUE THREAD

**Issue by Foxenz1** [BenCodez/VotifierPlus#52]
I’m getting this error on https://mcstatus.io/tools/vote when I configured everything correctly and put the correct username, how do I fix this? Btw I got a premium Java account not cracked

**Comment by BenCodez** [comment]
Send the full error?

**Comment by Foxenz1** [comment]
> Send the full error?

Its the title, console doesnt log anything

**Comment by BenCodez** [comment]
So where is that error from? That is not a votifierplus error.

**Comment by Foxenz1** [comment]
> So where is that error from? That is not a votifierplus error.

I said

**Comment by Foxenz1** [comment]
> So where is that error from? That is not a votifierplus error.

I said in the description, im using https://mcstatus.io/tools/vote to test votifierplus and it gives that error when i put correct IP port usernane and key

**Comment by BenCodez** [comment]
try this: https://mctools.org/votifier-tester

**Comment by Foxenz1** [comment]
> try this: https://mctools.org/votifier-tester

**Comment by Foxenz1** [comment]
> try this: https://mctools.org/votifier-tester

When i click send test vote it just redirects me to a blank page…?

**Comment by BenCodez** [comment]
Any better? https://mcservertime.com/votifier-tester

**Comment by Foxenz1** [comment]
> Any better? https://mcservertime.com/votifier-tester

Infinite loading screen, already tried nuVotifier and every other typa shit plugin with thousands of tutorials, i will simply give up on this
