### ISSUE TITLE
VotifierPlus Doesnt work on 1.20.6 PaperMC

### ISSUE THREAD

**Issue by TwoPointInfinity** [BenCodez/VotifierPlus#54]
using the latest stable build of paper along with VotifierPlus and whatever listener you prefer, i used votingpluign, votes will not be recieved. 

0. on a server using latest build of papermc 1.20.6
1. install votifierplus,
2. install votingplugin (optional)
3. configure correctly, choose a port, open port, bind host of necessary etc.
4. test vote on vote site.
Result: Vote not received, site will say cant connect. 

Expect result: Vote received.

**Comment by BenCodez** [comment]
Check out this guide: https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting

**Comment by TwoPointInfinity** [comment]
Thanks for reaching back to me benz, i've actually already read through this  and use alled the troubleshooting options listed here. 
I've even made sure to do the installation process and troubleshooting from many different guides and none seems to work. 
I've uninstalled, and reinstalled the plugin multiple times, using different keys and tokens. I've tried slightly different methods each time, if i can. Never have i been able to get a successful test vote to work from these sites, they all givv me an error on the website saying cant connect, and something along the lines of "the vote is coming from website-ip-address, please make sure you're firewall isnt blocking us and the ports are open"
this message has never showed up in my console or logs or anything similar for any of the votifiers i've used. 
`[VotifierPlus] Debug: Received vote record -> Vote (from:SERVICESITEHERE username:BenCodez address:Address `timeStamp:TestVote)`` i've tried a few different votifier tests sites just to be sure i touch a few different bases and im stuck at a stand still now after many days of working on this. 

If you get the chance, could you tell me if votifier works for you on 1.20.6? If it works for you, i know it has to be me then and i can keep experimenting with this cloud oracle firewall.

**Comment by TwoPointInfinity** [comment]
With the ports open, and in use by votifier, i turned off my firewall entirely and i was unable to get the test votes to come through to the server.

**Comment by BenCodez** [comment]
What's in your startup log for votifier? If your using a host contact them, they usually provide instructions for votifier, or even do it for you.

**Comment by TwoPointInfinity** [comment]
all the information you're asking for is provided in this thread, and in the link i posted in the OP. It appears that votifier is not attempting to use the provided port. other plugins like bluemap are using the ports, and the ports are open. 
My server is a Cloud Oracle server, running on Oracle Linux, similar to Centos 7. 
They are not a minecraft server host. With access to my machine's console I can open any and ALL ports if i choose to. I have tried many different ports and none of them work. 
Have you tried to reproduce this issue? Is it not present for you?

**Comment by TwoPointInfinity** [comment]
Entirely my fault, I had to add an ingress rule on cloud oracle website. Honestly a really complicated UI.
