### ISSUE TITLE
Error reading configuration file or RSA keys

### ISSUE THREAD

**Issue by cpt22** [BenCodez/VotifierPlus#7]
When installing plugin (clean install), this error is thrown and plugin does not load. The only file in the RSA folder is the public key (no private key).
<img width="630" alt="Screen Shot 2020-05-10 at 11 37 57 PM" src="https://user-images.githubusercontent.com/48806312/81524713-d678e700-9317-11ea-9a83-0ce6cdc881d1.png">

When I try to run the votifier plus command I receive this null pointer exception 
<img width="1135" alt="Screen Shot 2020-05-10 at 11 38 04 PM" src="https://user-images.githubusercontent.com/48806312/81524736-e8f32080-9317-11ea-8939-f9255f4eaf33.png">

And I also receive a null pointer exception when running the test command.

**Comment by Ben12345rocks** [comment]
http://ben12345rocks.com/job/VotingPlugin/

Should be good now. Delete your rsa folder.
