### ISSUE TITLE
Message with /say

### ISSUE THREAD

**Issue by whiskeytr** [BenCodez/VotifierPlus#79]
Hello, Im using VotifierPlus and Pinataparty and I have a problem like this.

![image](https://github.com/user-attachments/assets/6be04705-5a95-4d37-b50b-e7dc55ff2419)

Is that caused by PinataParty or VotifierPlus? I cant find anything in config.yml

**Comment by BenCodez** [comment]
Not from VotifierPlus, probably something else.

**Comment by whiskeytr** [comment]
Thanks.
