### ISSUE TITLE
help for install & setting

### ISSUE THREAD

**Issue by pinuxio** [BenCodez/VotifierPlus#9]
i'm looking for a guide to install it on my bungee 'but i can't find anything about it

**Comment by BenCodez** [comment]
Depends on your specific case and reward plugin.

**Comment by pinuxio** [comment]
VotingPlugin

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-PLUGINMESSAGING

Follow this
